"""
VibeGuard — Project Initializer
Initializes VibeGuard in a project, generates .cursorrules and scaffolds PROJECT_MEMORY.md.
"""

import os
import json
from pathlib import Path
from typing import Optional
from rich.console import Console
from rich.panel import Panel

console = Console()

IGNORE_DIRS = {"node_modules", "__pycache__", ".git", "dist", "build", ".next", "venv", ".venv"}


# ─── Stack detection ──────────────────────────────────────────────────────────

def _detect_stack(root: Path) -> dict:
    """Detect tech stack. Handles monorepos by scanning ALL package.json files."""
    stack = {
        "language": "unknown",
        "framework": None,
        "package_manager": None,
        "has_tests": False,
        "has_docker": False,
        "has_ci": False,
        "is_monorepo": False,
        "sub_packages": [],
    }

    files = set()
    all_pkg_jsons = []

    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in IGNORE_DIRS and not d.startswith(".")]
        for f in filenames:
            files.add(f.lower())
        if "package.json" in filenames:
            all_pkg_jsons.append(Path(dirpath) / "package.json")

    # Monorepo = more than 1 package.json found
    if len(all_pkg_jsons) > 1:
        stack["is_monorepo"] = True

    if all_pkg_jsons:
        stack["language"] = "JavaScript/TypeScript"
        stack["package_manager"] = "npm"
        if "yarn.lock" in files:
            stack["package_manager"] = "yarn"
        if "pnpm-lock.yaml" in files:
            stack["package_manager"] = "pnpm"
        if "bun.lockb" in files:
            stack["package_manager"] = "bun"

        # Scan every package.json found for framework detection
        frameworks_found = []
        for pkg_path in all_pkg_jsons:
            try:
                pkg = json.loads(pkg_path.read_text(encoding="utf-8"))
                deps = {**pkg.get("dependencies", {}), **pkg.get("devDependencies", {})}
                rel = str(pkg_path.parent.relative_to(root))
                pkg_name = pkg.get("name", rel)

                fw = None
                if "next" in deps:
                    fw = "Next.js"
                elif "vite" in deps:
                    fw = "Vite"
                elif "react" in deps:
                    fw = "React"
                elif "vue" in deps:
                    fw = "Vue"
                elif "svelte" in deps:
                    fw = "Svelte"
                elif "@nestjs/core" in deps:
                    fw = "NestJS"
                elif "express" in deps or "fastify" in deps or "koa" in deps:
                    fw = "Express/Node API"

                if fw:
                    label = f"{fw} [{pkg_name}]"
                    frameworks_found.append(label)
                    stack["sub_packages"].append({
                        "name": pkg_name,
                        "path": rel,
                        "framework": fw,
                    })
            except Exception:
                pass

        if frameworks_found:
            stack["framework"] = " + ".join(frameworks_found)

    elif "requirements.txt" in files or "pyproject.toml" in files or "setup.py" in files:
        stack["language"] = "Python"
        stack["package_manager"] = "pip"
        pyproject = root / "pyproject.toml"
        if pyproject.exists():
            try:
                content = pyproject.read_text(encoding="utf-8").lower()
                if "fastapi" in content:
                    stack["framework"] = "FastAPI"
                elif "django" in content:
                    stack["framework"] = "Django"
                elif "flask" in content:
                    stack["framework"] = "Flask"
                elif "torch" in content:
                    stack["framework"] = "PyTorch"
            except Exception:
                pass

    elif "go.mod" in files:
        stack["language"] = "Go"
        stack["package_manager"] = "go modules"
    elif "cargo.toml" in files:
        stack["language"] = "Rust"
        stack["package_manager"] = "cargo"
    elif "pom.xml" in files:
        stack["language"] = "Java"
        stack["package_manager"] = "Maven"
        stack["framework"] = "Spring (likely)"

    stack["has_docker"] = "dockerfile" in files or "docker-compose.yml" in files
    stack["has_ci"] = ".github" in {d.lower() for d in os.listdir(root)} or ".gitlab-ci.yml" in files
    stack["has_tests"] = any(
        f.startswith("test_") or f.endswith(("_test.py", ".test.js", ".test.ts", ".spec.ts", ".spec.js"))
        for f in files
    )

    return stack


# ─── .cursorrules generation ──────────────────────────────────────────────────

_CURSORRULES_TEMPLATE = """# .cursorrules — Generated by VibeGuard
# These rules help Cursor AI act like a senior developer on YOUR project.

## Project Context
- Language: {language}{framework_line}
- Package Manager: {package_manager}{monorepo_line}

## Core Rules

### 1. Memory First
- Always read PROJECT_MEMORY.md at the start of every session.
- Never assume you know the project structure without checking.
- When making changes, cross-reference the function list in PROJECT_MEMORY.md.

### 2. Zero-Regression Policy
- Before deleting or renaming any function/class/export, verify no other file imports it.
- If you remove a public API, explicitly list all files that need updating.
- Never remove error handling silently.

### 3. Code Style
- Match the existing code style in each file -- do not impose new patterns.
- If you see a pattern used 3+ times, follow it. Do not introduce new patterns without asking.
- Preserve all existing comments and docstrings unless explicitly asked to remove them.

### 4. Change Protocol
- For any change > 50 lines, explain your plan BEFORE writing code.
- List the files you will modify and why.
- If a change affects an entry point ({entry_points}), be extra careful.

### 5. Testing
{test_rule}

### 6. When Uncertain
- Say "I'm not sure" rather than guessing.
- If you need more context, ask for the relevant file content.
- Run `vibeguard scan` to refresh PROJECT_MEMORY.md if context seems stale.

## Anti-Patterns to Avoid
- Do NOT delete files without checking imports
- Do NOT change function signatures without updating all call sites
- Do NOT add dependencies without checking if one already exists
- Do NOT ignore existing error handling patterns

## When Adding New Features
1. Check PROJECT_MEMORY.md for existing utilities you can reuse
2. Follow the existing file/folder naming convention
3. Add the new function/class to PROJECT_MEMORY.md scope

_Rules enforced by VibeGuard -- run `vibeguard scan` to update PROJECT_MEMORY.md_
"""


def _generate_cursorrules(stack: dict, root: Path) -> str:
    framework_line = f"\n- Framework: {stack['framework']}" if stack.get("framework") else ""
    monorepo_line = "\n- Structure: Monorepo (multiple packages)" if stack.get("is_monorepo") else ""
    pkg_mgr = stack["package_manager"] or "unknown"

    entry_points_map = {
        "Python": "main.py / app.py",
        "JavaScript/TypeScript": "index.js / index.ts / src/index.ts",
        "Go": "main.go",
        "Rust": "main.rs",
    }
    entry_points = entry_points_map.get(stack["language"], "main entry file")

    if stack["has_tests"]:
        test_rule = "- Always add a test when adding new functionality.\n- Run tests before committing changes."
    else:
        test_rule = "- This project has no tests yet. Consider adding tests for critical functions."

    return _CURSORRULES_TEMPLATE.format(
        language=stack["language"],
        framework_line=framework_line,
        monorepo_line=monorepo_line,
        package_manager=pkg_mgr,
        entry_points=entry_points,
        test_rule=test_rule,
    )


# ─── Init ─────────────────────────────────────────────────────────────────────

def run_init(target_dir: Optional[str] = None) -> None:
    root = Path(target_dir) if target_dir else Path.cwd()

    console.print(f"\n[bold green]VibeGuard Initializer[/bold green]")
    console.print(f"[dim]Project: {root}[/dim]\n")

    console.print("[cyan]Detecting tech stack...[/cyan]")
    stack = _detect_stack(root)

    lang_str = f"[bold]{stack['language']}[/bold]"
    if stack.get("framework"):
        lang_str += f" / [bold]{stack['framework']}[/bold]"
    console.print(f"  Language:   {lang_str}")
    console.print(f"  Pkg Mgr:    [cyan]{stack['package_manager'] or 'unknown'}[/cyan]")
    console.print(f"  Monorepo:   [cyan]{stack['is_monorepo']}[/cyan]")
    console.print(f"  Has Tests:  [{'green' if stack['has_tests'] else 'red'}]{stack['has_tests']}[/{'green' if stack['has_tests'] else 'red'}]")
    console.print(f"  Has Docker: [cyan]{stack['has_docker']}[/cyan]")
    console.print(f"  Has CI:     [cyan]{stack['has_ci']}[/cyan]")

    if stack["sub_packages"]:
        console.print(f"\n  [bold]Packages detected:[/bold]")
        for sp in stack["sub_packages"]:
            console.print(f"    [dim]-[/dim] [yellow]{sp['path']}[/yellow]  ({sp['framework']})")

    # Create .vibeguard config dir
    vg_dir = root / ".vibeguard"
    vg_dir.mkdir(exist_ok=True)
    (vg_dir / "stack.json").write_text(json.dumps(stack, indent=2), encoding="utf-8")

    # Generate .cursorrules
    cursorrules_content = _generate_cursorrules(stack, root)
    (root / ".cursorrules").write_text(cursorrules_content, encoding="utf-8")

    # Scaffold PROJECT_MEMORY.md if it doesn't exist
    memory_path = root / "PROJECT_MEMORY.md"
    if not memory_path.exists():
        scaffold = (
            "# PROJECT_MEMORY.md\n"
            "> Run `vibeguard scan` to auto-populate this file.\n\n"
            "```bash\n"
            "python vibeguard.py scan\n"
            "python vibeguard.py score\n"
            "python vibeguard.py guard\n"
            "```\n"
        )
        memory_path.write_text(scaffold, encoding="utf-8")

    console.print(f"\n[bold green]VibeGuard initialized![/bold green]")
    console.print(f"\n  [cyan].cursorrules[/cyan]          Cursor AI guardrails (stack-aware)")
    console.print(f"  [cyan].vibeguard/stack.json[/cyan]  Detected stack config")
    console.print(f"  [cyan]PROJECT_MEMORY.md[/cyan]      Scaffold (run scan to populate)")

    console.print(Panel(
        "Next steps:\n"
        "  1. [cyan]vibeguard scan[/cyan]   -- index codebase -> PROJECT_MEMORY.md\n"
        "  2. [cyan]vibeguard score[/cyan]  -- health score\n"
        "  3. Paste [cyan]PROJECT_MEMORY.md[/cyan] at the start of every AI session",
        border_style="green",
        padding=(1, 2),
    ))
