"""
VibeGuard — Project Genesis Engine
Turns a rough idea into a complete project blueprint.
Generates: PRD, Architecture, Database Schema, API Spec, User Stories, Dev Plan.
No Figma needed. No documents needed. Just your idea.
"""

import json
from pathlib import Path
from datetime import datetime
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.prompt import Prompt, Confirm
from rich.table import Table
from rich.rule import Rule
from .llm_gateway import get_llm_client

console = Console(force_terminal=True)


# ─── Smart Interview ────────────────────────────────────────────────────────────

def _interview_user(client, raw_idea: str) -> dict:
    """
    Interview the user like a senior PM would.
    Extract enough information to write a professional PRD.
    """
    console.print("\n[bold yellow]🎤 Phase 1: Requirements Interview[/bold yellow]")
    console.print("[dim]I'll ask you a few questions so I can build this exactly right.[/dim]\n")

    # Generate smart questions based on the idea
    question_prompt = f"""You are a Senior Product Manager at a top tech company.
A client/developer gave you this rough idea: "{raw_idea}"

Generate 6 targeted questions that will help you understand exactly what to build.
Cover: target users, core features, scale, tech preferences, monetization, timeline.
Keep questions SHORT and clear. Non-technical person should understand them.

Return ONLY JSON:
{{
  "app_category": "web app / mobile / CLI / API / etc",
  "questions": [
    {{"id": 1, "question": "Who is the primary user of this?", "example": "e.g. Students, small business owners, developers"}},
    {{"id": 2, "question": "...", "example": "..."}}
  ]
}}"""

    with Progress(SpinnerColumn(), TextColumn("Analyzing your idea..."), transient=True) as p:
        p.add_task("", total=None)
        response = client.chat(
            messages=[{"role": "user", "content": question_prompt}],
            temperature=0.3, max_tokens=1000,
        )

    qdata = _parse_json(response)
    questions = qdata.get("questions", [])

    answers = {"raw_idea": raw_idea, "app_category": qdata.get("app_category", "web app")}

    for q in questions:
        qtext = q.get("question", "")
        example = q.get("example", "")
        if not qtext:
            continue
        hint = f"[dim]{example}[/dim]" if example else ""
        if hint:
            console.print(f"  {hint}")
        answer = Prompt.ask(f"  [cyan]{qtext}[/cyan]")
        answers[qtext] = answer
        console.print()

    return answers


# ─── Document Generation ────────────────────────────────────────────────────────

def _generate_prd(client, answers: dict, output_dir: Path) -> str:
    """Generate a professional PRD (Product Requirements Document)."""
    context = _format_answers(answers)

    prompt = f"""You are a Senior Product Manager at Google/Amazon level.
Write a complete, professional PRD for this project.

PROJECT CONTEXT:
{context}

Write a detailed PRD with these sections:
1. Executive Summary
2. Problem Statement  
3. Target Users & Personas
4. Core Features (with priority: P0/P1/P2)
5. User Stories ("As a [user], I want to [action] so that [benefit]")
6. Non-Functional Requirements (performance, security, scale)
7. Success Metrics & KPIs
8. Out of Scope (for v1)

Make it production-level. Think like this will serve 1 million users.
Write in clean Markdown. Be specific, not generic."""

    with Progress(SpinnerColumn(), TextColumn("Writing PRD..."), transient=True) as p:
        p.add_task("", total=None)
        prd = client.chat(messages=[{"role": "user", "content": prompt}], temperature=0.3, max_tokens=4000)

    path = output_dir / "PRD.md"
    path.write_text(f"# Product Requirements Document\n*Generated by VibeGuard Genesis — {datetime.now().strftime('%Y-%m-%d')}*\n\n{prd}", encoding="utf-8")
    return str(path)


def _generate_architecture(client, answers: dict, output_dir: Path) -> str:
    """Generate a complete system architecture document."""
    context = _format_answers(answers)

    prompt = f"""You are a Principal Engineer and Solution Architect at a FAANG company.
Design a complete production-grade system architecture for this project.

PROJECT CONTEXT:
{context}

Write a detailed architecture document covering:
1. Tech Stack Decision (with exact versions and WHY each was chosen)
2. System Architecture Diagram (as ASCII art or Mermaid)
3. Frontend Architecture (components, state management, routing)
4. Backend Architecture (API design, services, middleware)
5. Database Design (which DB, why, table/collection structure)
6. Authentication & Authorization approach
7. Caching Strategy
8. File/Media Storage
9. Deployment Architecture (hosting, CI/CD, environments)
10. Security Considerations
11. Performance at Scale (how it handles 100K+ users)
12. Project Folder Structure (complete file tree)

Be extremely specific. No "we can use X or Y" — make decisions like a senior engineer.
Write in clean Markdown with Mermaid diagrams where helpful."""

    with Progress(SpinnerColumn(), TextColumn("Designing architecture..."), transient=True) as p:
        p.add_task("", total=None)
        arch = client.chat(messages=[{"role": "user", "content": prompt}], temperature=0.2, max_tokens=4000)

    path = output_dir / "ARCHITECTURE.md"
    path.write_text(f"# System Architecture\n*Generated by VibeGuard Genesis — {datetime.now().strftime('%Y-%m-%d')}*\n\n{arch}", encoding="utf-8")
    return str(path)


def _generate_database_schema(client, answers: dict, output_dir: Path) -> str:
    """Generate complete database schema."""
    context = _format_answers(answers)

    prompt = f"""You are a Senior Database Architect.
Design a complete, production-ready database schema for this project.

PROJECT CONTEXT:
{context}

Provide:
1. Database choice and justification (PostgreSQL/MongoDB/etc)
2. Complete schema with ALL tables/collections
3. For each table: fields, data types, constraints, indexes
4. Relationships (foreign keys, embedding strategy)
5. Indexes for performance
6. Example SQL CREATE statements (or MongoDB schemas)
7. Seed data examples

Think about: data integrity, query performance, scalability.
Write in clean Markdown with code blocks for SQL/JSON."""

    with Progress(SpinnerColumn(), TextColumn("Designing database schema..."), transient=True) as p:
        p.add_task("", total=None)
        schema = client.chat(messages=[{"role": "user", "content": prompt}], temperature=0.2, max_tokens=3000)

    path = output_dir / "DATABASE_SCHEMA.md"
    path.write_text(f"# Database Schema\n*Generated by VibeGuard Genesis — {datetime.now().strftime('%Y-%m-%d')}*\n\n{schema}", encoding="utf-8")
    return str(path)


def _generate_api_spec(client, answers: dict, output_dir: Path) -> str:
    """Generate complete REST API specification."""
    context = _format_answers(answers)

    prompt = f"""You are a Senior Backend Engineer.
Design a complete REST API specification for this project.

PROJECT CONTEXT:
{context}

Provide:
1. Base URL structure and versioning strategy
2. Authentication endpoints (register, login, refresh, logout)
3. ALL other endpoints grouped by resource
   For each endpoint: Method, URL, Request body, Response, Error codes
4. Common response format (success/error wrapper)
5. Rate limiting strategy
6. Example curl commands for key endpoints

Write as a developer-ready API spec in clean Markdown."""

    with Progress(SpinnerColumn(), TextColumn("Writing API specification..."), transient=True) as p:
        p.add_task("", total=None)
        api = client.chat(messages=[{"role": "user", "content": prompt}], temperature=0.2, max_tokens=3000)

    path = output_dir / "API_SPEC.md"
    path.write_text(f"# API Specification\n*Generated by VibeGuard Genesis — {datetime.now().strftime('%Y-%m-%d')}*\n\n{api}", encoding="utf-8")
    return str(path)


def _generate_dev_plan(client, answers: dict, output_dir: Path) -> str:
    """Generate a sprint-by-sprint development plan."""
    context = _format_answers(answers)

    prompt = f"""You are a Senior Engineering Manager.
Create a realistic, detailed development plan for this project.

PROJECT CONTEXT:
{context}

Create:
1. Development phases (MVP → Beta → Production)
2. Sprint breakdown (2-week sprints) with specific tasks
3. Priority order (what to build first and why)
4. Potential technical risks and mitigation
5. Definition of Done for each phase
6. Launch checklist (what must work before going live)

Also generate: The PERFECT prompt to paste into Cursor/Claude/ChatGPT to start building.
This prompt should include all context, tech stack, and constraints so the AI builds it correctly on the first try.

Write in clean Markdown."""

    with Progress(SpinnerColumn(), TextColumn("Writing development plan..."), transient=True) as p:
        p.add_task("", total=None)
        plan = client.chat(messages=[{"role": "user", "content": prompt}], temperature=0.3, max_tokens=3000)

    path = output_dir / "DEV_PLAN.md"
    path.write_text(f"# Development Plan\n*Generated by VibeGuard Genesis — {datetime.now().strftime('%Y-%m-%d')}*\n\n{plan}", encoding="utf-8")
    return str(path)


def _generate_cursor_rules(client, answers: dict, output_dir: Path) -> str:
    """Generate a .cursorrules file tailored to this exact project."""
    context = _format_answers(answers)

    prompt = f"""You are a Senior Engineer setting up a new project.
Create a detailed .cursorrules file that will make Cursor AI behave like a senior developer on THIS specific project.

PROJECT CONTEXT:
{context}

The .cursorrules must include:
1. Project-specific tech stack rules
2. Naming conventions for this project
3. File structure rules
4. Code style requirements
5. What to NEVER do (anti-patterns for this project)
6. How to handle errors in this project's style
7. Testing requirements
8. Performance rules (specific to this app's scale)
9. Security rules (specific to this app's data)
10. Instruction to always read PROJECT_MEMORY.md before any change

Write as a production .cursorrules file. Be very specific to THIS project, not generic."""

    with Progress(SpinnerColumn(), TextColumn("Generating project rules..."), transient=True) as p:
        p.add_task("", total=None)
        rules = client.chat(messages=[{"role": "user", "content": prompt}], temperature=0.2, max_tokens=2000)

    path = output_dir / ".cursorrules"
    path.write_text(rules, encoding="utf-8")
    return str(path)


def _generate_ai_prompt(client, answers: dict, output_dir: Path) -> str:
    """Generate the perfect AI prompt to start building immediately."""
    context = _format_answers(answers)

    prompt = f"""You are an expert AI prompt engineer.
Create the PERFECT prompt that a developer can paste directly into Cursor, Claude, or ChatGPT to start building this project.

PROJECT CONTEXT:
{context}

The perfect build prompt must:
1. Give full context about what's being built
2. Specify exact tech stack and versions
3. List the most important features to build first
4. Specify code quality standards
5. Tell the AI what NOT to do
6. Specify the folder structure
7. Be self-contained (AI needs no other context)

Also create 3 follow-up prompts for:
- Adding authentication
- Adding the database layer  
- Deploying to production

Format: Ready to copy-paste. Include separators between prompts."""

    with Progress(SpinnerColumn(), TextColumn("Crafting AI prompts..."), transient=True) as p:
        p.add_task("", total=None)
        ai_prompt = client.chat(messages=[{"role": "user", "content": prompt}], temperature=0.3, max_tokens=2000)

    path = output_dir / "AI_PROMPTS.md"
    path.write_text(f"# Ready-to-Use AI Prompts\n*Generated by VibeGuard Genesis — {datetime.now().strftime('%Y-%m-%d')}*\n\n{ai_prompt}", encoding="utf-8")
    return str(path)


# ─── Main Entry Point ───────────────────────────────────────────────────────────

def run_genesis(idea: str, output_dir: str = None) -> None:
    """
    Full Project Genesis pipeline.
    From rough idea → complete project blueprint ready to build.
    """
    # Setup output directory
    if output_dir and output_dir != ".":
        root = Path(output_dir)
    else:
        # Create a project folder based on the idea
        slug = idea[:30].lower().replace(" ", "-").replace("/", "-")
        slug = "".join(c for c in slug if c.isalnum() or c == "-")
        root = Path.cwd() / f"{slug}-docs"

    root.mkdir(parents=True, exist_ok=True)

    console.print(Panel(
        f"[bold cyan]Project Genesis Engine[/bold cyan]\n\n"
        f"[white]Idea:[/white] {idea}\n"
        f"[white]Output:[/white] {root}\n\n"
        f"[dim]I'll turn your rough idea into a complete project blueprint.\n"
        f"PRD · Architecture · Database · API · Dev Plan · AI Prompts[/dim]",
        border_style="cyan",
        padding=(1, 2),
    ))

    # Get LLM client
    try:
        client = get_llm_client()
    except RuntimeError:
        console.print(Panel(
            "[bold red]No AI provider configured![/bold red]\n\n"
            "Run first: [bold cyan]python vibeguard.py config[/bold cyan]",
            border_style="red",
        ))
        return

    # Phase 1: Interview
    answers = _interview_user(client, idea)

    console.print(Rule("[bold cyan]Generating Your Project Blueprint[/bold cyan]"))
    console.print("[dim]This takes 2-3 minutes. Generating 6 professional documents...[/dim]\n")

    # Generate all documents
    docs_generated = []

    try:
        path = _generate_prd(client, answers, root)
        docs_generated.append(("PRD.md", "Product Requirements Document", path))
        console.print("  [green]✓[/green] PRD.md")
    except Exception as e:
        console.print(f"  [red]✗[/red] PRD failed: {e}")

    try:
        path = _generate_architecture(client, answers, root)
        docs_generated.append(("ARCHITECTURE.md", "System Architecture", path))
        console.print("  [green]✓[/green] ARCHITECTURE.md")
    except Exception as e:
        console.print(f"  [red]✗[/red] Architecture failed: {e}")

    try:
        path = _generate_database_schema(client, answers, root)
        docs_generated.append(("DATABASE_SCHEMA.md", "Database Schema", path))
        console.print("  [green]✓[/green] DATABASE_SCHEMA.md")
    except Exception as e:
        console.print(f"  [red]✗[/red] Database schema failed: {e}")

    try:
        path = _generate_api_spec(client, answers, root)
        docs_generated.append(("API_SPEC.md", "REST API Specification", path))
        console.print("  [green]✓[/green] API_SPEC.md")
    except Exception as e:
        console.print(f"  [red]✗[/red] API spec failed: {e}")

    try:
        path = _generate_dev_plan(client, answers, root)
        docs_generated.append(("DEV_PLAN.md", "Development Plan & Sprints", path))
        console.print("  [green]✓[/green] DEV_PLAN.md")
    except Exception as e:
        console.print(f"  [red]✗[/red] Dev plan failed: {e}")

    try:
        path = _generate_ai_prompt(client, answers, root)
        docs_generated.append(("AI_PROMPTS.md", "Ready-to-Use AI Prompts", path))
        console.print("  [green]✓[/green] AI_PROMPTS.md")
    except Exception as e:
        console.print(f"  [red]✗[/red] AI prompts failed: {e}")

    try:
        path = _generate_cursor_rules(client, answers, root)
        docs_generated.append((".cursorrules", "Cursor AI Rules", path))
        console.print("  [green]✓[/green] .cursorrules")
    except Exception as e:
        console.print(f"  [red]✗[/red] cursorrules failed: {e}")

    # Save answers as context file
    context_path = root / "GENESIS_CONTEXT.json"
    context_path.write_text(json.dumps(answers, indent=2), encoding="utf-8")

    # Summary
    console.print()
    console.print(Panel(
        f"[bold green]✅ Blueprint Complete![/bold green]\n\n"
        f"[white]{len(docs_generated)} documents generated in:[/white]\n"
        f"[cyan]{root}[/cyan]\n\n"
        f"[bold white]What to do next:[/bold white]\n"
        f"  1. Read [cyan]PRD.md[/cyan] to understand what you're building\n"
        f"  2. Read [cyan]ARCHITECTURE.md[/cyan] for the tech decisions\n"
        f"  3. Open [cyan]AI_PROMPTS.md[/cyan] and paste Prompt #1 into Cursor\n"
        f"  4. Run [cyan]vibeguard build[/cyan] to auto-build the whole project\n\n"
        f"[dim]Your .cursorrules is pre-configured for this exact project.[/dim]",
        border_style="green",
        padding=(1, 2),
    ))

    # Ask if they want to start building now
    console.print()
    if Confirm.ask("[bold]Start building the project right now?[/bold]", default=True):
        from .autonomous_agent import run_build
        build_prompt = f"{idea}\n\nReference documents are in: {root}"
        run_build(build_prompt, str(Path.cwd()))


# ─── Helpers ────────────────────────────────────────────────────────────────────

def _format_answers(answers: dict) -> str:
    lines = []
    for k, v in answers.items():
        if k not in ("raw_idea",):
            lines.append(f"- {k}: {v}")
    return "\n".join(lines)


def _parse_json(text: str) -> dict:
    import re
    try:
        if "```json" in text:
            text = text.split("```json")[1].split("```")[0]
        elif "```" in text:
            text = text.split("```")[1].split("```")[0]
        return json.loads(text.strip())
    except Exception:
        match = re.search(r'\{.*\}', text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except Exception:
                pass
    return {"questions": []}
